### ISSUE TITLE
can not access to enedis data since mid may 2021

### ISSUE THREAD

**Issue by niouflex49** [YunoHost-Apps/aeneria_ynh#14]
### Describe the bug
I can not receive any data from Enedis since mid may 2021 after 5 months of good behaviour 

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 1.1.3~ynh1
- I have access to my server: *Through SSH or through the webadmin | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch:installed the testing branch
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

goto rafraichir les données
put a date
and refresh

### Expected behavior

*A clear and concise description of what you expected to happen. You can remove this section if the command above is enough to understand your intent.*
when trying to refresh the enedis data, just get an error message, see below

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*
- *In the webadmin, the error message contains a link to the relevant log page. On that page, you will be able to 'Share with Yunopaste'. If you missed it, the logs of previous operations are also available under Tools > Logs.*
- *In command line, the command to share the logs is displayed at the end of the operation and looks like `yunohost log display [log name] --share`. If you missed it, you can find the log ID of a previous operation using `yunohost log list`.*

*After sharing the log, please copypaste directly the link provided by YunoHost (to help readability, no need to copypaste the entire content of the log here, just the link is enough...)*

*If applicable and useful, add screenshots to help explain your problem.*

Il y a eu une erreur pour XXXXXXXXXXX,  France pour la date du 01/06/2021 : '<!DOCTYPE html> <html> <head> <meta charset="UTF-8" /> <meta name="robots" content="noindex,nofollow,noarchive" /> <title>An Error Occurred: Forbidden</title> <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; } .container { margin: 30px; max-width: 600px; } h1 { color: #dc3545; font-size: 24px; } h2 { font-size: 18px; }</style> </head> <body> <div class="container"> <h1>Oops! An Error Occurred</h1> <h2>The server returned a "403 Forbidden".</h2> <p> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. </p> </div> </body> </html>'

**Comment by SimonMellerin** [comment]
Hi,

See here to have more information about your issue https://gitlab.com/aeneria/aeneria-app/-/issues/19

Can you try to re-ask for consent for your linky ? It could solve your problem.

If it don't, let me know

Simon

**Comment by niouflex49** [comment]
Bonjour
Cest ok pour mon link sur une adresse
Quand je donne l’accord a aeneria pour accéder à mes données ENEDIS….error
Pourtant je reçois l’email d'enedis qui dit que cest ok
Si tu peux m’aider..
Cdlt pascal

On 23 Jun 2021, at 10:22, Simon MELLERIN ***@***.******@***.***>> wrote:



Hi,

See here to have more information about your issue https://gitlab.com/aeneria/aeneria-app/-/issues/19

Can you try to re-ask for consent for your linky ? It could solve your problem.

If it don't, let me know

Simon

**Comment by nchopin14** [comment]
Depuis juin, plus de mise à jour des consos. J'ai essayé de supprimer puis de refaire le consentement mais je tombe sur erreur 500.
Plus moyen de configurer l'accès... Bientot une mise à jour salvatrice ?

**Comment by SimonMellerin** [comment]
Bonjour,

Ce bug sera résolu avec la version 1.15 qui devrait bien arrivé https://github.com/YunoHost-Apps/aeneria_ynh/issues/16

**Comment by SimonMellerin** [comment]
La MR de mise à jour vers la version 1.15 a été mergée dans master.

@nchopin14  ou @niouflex49  je vous laisse fermer ce ticket si c'est ok pourvous
