### ISSUE TITLE
Can't access to configuration page

### ISSUE THREAD

**Issue by urschuca** [YunoHost-Apps/aeneria_ynh#16]
### Describe the bug

I can't access to the configuration page

### Context

- Hardware: *VPS bought online* 
- YunoHost version: __4.2.6.1__
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

```
# yunohost app info aeneria
description: Dashboard to analyse your energy consumption data from Linky & weather
domain_path: urschuca.com/aeneria
name: aeneria
version: 1.1.3~ynh1
```

### Steps to reproduce

Each time I click on the configuration links I get 

```
Oups'

Désolé, une erreur est survenue !

Si cette erreur persiste, merci de nous contacter.
```

### Expected behavior

Access to the configuration page

### Logs

```
# tail /var/www/aeneria/var/log/prod-php-2021-08-04.log
...
[2021-08-04T13:53:44.876312+00:00] php.CRITICAL: Uncaught Error: Return value of App\Twig\AppExtension::getLinkyDescription() must be an instance of Aeneria\EnedisDataConnectApi\Model\Address or null, string returned {"exception":"[object] (TypeError(code: 0): Return value of App\\Twig\\AppExtension::getLinkyDescription() must be an instance of Aeneria\\EnedisDataConnectApi\\Model\\Address or null, string returned at /var/www/aeneria/src/Twig/AppExtension.php:150)"} []
```

edit : formating

**Comment by SimonMellerin** [comment]
Thanks for reporting this, I'm gonna check that

**Comment by sysblade** [comment]
I confirm I have the exact same issue.

**Comment by NoWiS-** [comment]
Hello, 

A fix already exist  https://gitlab.com/aeneria/aeneria-app/-/commit/3e0de977a99e75c63a2ec873e848e60b39f99528
(I applied it manually , and it works perfectly. The path is  `/var/www/aeneria/src/Twig/AppExtension.php`)

There's already a pull request https://github.com/YunoHost-Apps/aeneria_ynh/pull/15 to bump the version of aeneria to 1.1.5. Can I do something to help its approval ?

**Comment by SimonMellerin** [comment]
Right, don't know why this PR haven't been merged yet. 

I've merged it.

Let's wait for tests to be ok here : https://github.com/YunoHost-Apps/aeneria_ynh/pull/17 and then it should be ok to merge it to master

**Comment by SimonMellerin** [comment]
Should be ok now with last update.

@kedare or @NoWiS-  Feel free to close this issue if it's ok for you

**Comment by NoWiS-** [comment]
I updated my instance, and it works, thanks !

(I haven't however the right to close the issue)
