### ISSUE TITLE
[Heat map Days/Weeks] Very very small graphic bug

### ISSUE THREAD

**Issue by A-Nicoladie** [YunoHost-Apps/aeneria_ynh#29]
### Describe the bug

On power consumption graph, if the end of the year doesn't stop on sunday, some days are missing

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | Through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: aeneria 1.1.6

#### Current behavior

![image](https://user-images.githubusercontent.com/90625228/158782783-ba5a048f-58a7-4cc1-b0ff-0fcb2a158573.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/90625228/158784974-c0bdd4d6-7ab9-46de-b4bb-1294303440ba.png)

**Comment by tituspijean** [comment]
I would guess this is to be fixed upstream ; what do you think @SimonMellerin?

**Comment by SimonMellerin** [comment]
yes exactly,

Below a comment from [yunohost forum](https://forum.yunohost.org/t/aeneria-a-little-dashboard-to-analyse-your-electricity-consumption-data/13986/76?u=enuts) on this particular bug :

> 
> ah oui, c’est un vieux bug à cause des numéros de semaine… je croyais avoir réglé ce souci… les données doivent être bien présentes, c’est uniquement l’affichage qui merdouille…
> 
> Je suis en train de faire une refonte graphique de l’ui, ce problème ne devrait plus exister dans le futur. Mais je ne peux pas vraiment dire quand j’aurais fini de travailler dessus.
> 
> Tout ça pour dire que je ne pense pas corriger ce bug sur la version actuelle. Pour avoir la donnée manquante, tu peux passer par l’onglet ‘Électricité’ et le graphique ’ Évolution de la consommation’
> 
> Désolé pour ce petit bug et merci pour ton retour :wink:

Simon
