### ISSUE TITLE
Update version ? Gaz?

### ISSUE THREAD

**Issue by ndx1905-github** [YunoHost-Apps/aeneria_ynh#30]
### Context

Yuno version is 1.1.6, and UI is different than the one on Aeneris website  : square dots instead of circles.. that's just UI, but aeneria now features a new version that add gaz information.
On their git, it's the "new" branch. Anyway yuno host can add a different more up to date branch ?

See running demo from aeneria : https://demo.aeneria.com/

vs aging version on yuno 

(testing branch from yuno is far behind)

**Comment by tituspijean** [comment]
With a little bit more investigating, you would have seen that the latest available stable release is 1.1.6 and that the demo website runs a beta version of the software.

Patience. 😀

**Comment by SimonMellerin** [comment]
Hi,

Yep the demo website runs on the last beta version.

The version 2 of æneria will includes gazpar. It should be available soon but i need to test it a little bit more.

I may provide a beta-test version for yunohost for people who want to help me validate it ;) 
(most æneria user come from yunohost)
