### ISSUE TITLE
Connexion impossible

### ISSUE THREAD

**Issue by shinizoka** [YunoHost-Apps/aeneria_ynh#40]
Je n'arrive pas à me connecter à l'application, je reçois le message « Identifiants invalides. »

Context
- Hardware: machine virtuelle sur Freebox Delta
- YunoHost version: 11.2.5
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

La petite histoire :
Je viens d'installer yunohost sur ma freebox, surtout pour tester et bidouiller et une fois installé, je cherche une première application à essayer et je tombe sur æneria dont je trouve le concept intéressant.
Je l'installe via yunohost donc en précisant un utilisateur administrateur, l'installation se passe bien.
**Mais lorsque je vais dans l'application, je n'arrive pas à m'y connecter. Je précise bien l'email que je vois dans la fiche utilisateur yunohost correspondant à l'administrateur que j'ai saisi lors de l'installation, ainsi que son mot de passe, mais ça ne fonctionne pas, pour une raison indéterminée.**
J'ai tenté de créer un 2e utilisateur du groupe admin dans yunohost, puis de désinstaller / réinstaller æneria avec ce nouvel utilisateur, sans succès : j'ai toujours le même comportement.

Peut-être que le souci vient de yunohost mais étant un nouvel utilisateur je ne sais pas comment m'en assurer.

Un peu d'aide serait la bienvenue. Merci 👍

**Comment by MokuJinJin** [comment]
J'ai le même problème.

J'ai dû changer le mot de passe dans aeneria (via SHH), je pense que le [script d'install ne donne pas le bon mot de passe](https://github.com/YunoHost-Apps/aeneria_ynh/blob/37dcc93af2e6e38dc0b36c817703a90e5c42727e/scripts/install#L63) qui donne une connexion impossible.

Cette commande permet de modifier le mot de passe de l'utilisateur de aeneria, en utilisant son login (le mail de l'utilisateur fournit à l'installation)
Commande à faire via SSH, sur le serveur.

```bash
/var/www/aeneria/bin/console aeneria:user:edit -p secret_password admin@exemple.com
```

Un peu barbare comme contournement, mais ça fonctionne.

**Comment by shinizoka** [comment]
Merci, j'ai pu me connecter après avoir modifié ainsi le mot de passe.
Bon maintenant j'ai un souci pour le partage des données depuis Enedis, où la page me retourne une erreur 500.

J'essaierai à nouveau un peu plus tard, des fois que ça vienne effectivement de chez eux, comme le laisse supposer le code d'erreur…

**Comment by MokuJinJin** [comment]
Pareil de mon côté, je suis allé voir sur le git de l'application et j'ai trouvé ça https://gitlab.com/aeneria/aeneria-app/-/issues/36

En changeant un peu l'URL, j'ai réussi à passer l'erreur côté enedis, mais juste après avoir accepté côté enedis, j'ai un erreur côté aeneria : un erreur est survenue.

Bref autant de manip pour arriver à un truc qui ne marche pas, j'ai abandonné

**Comment by shinizoka** [comment]
Oui je comprends, c'est dommage, l'idée était attirante sur le papier.
Et en effet, le lien vers l'autre bug n'a pas avancé depuis quelques mois.

Merci en tout cas pour cet échange et à l'auteur d'æneria pour le travail, en espérant que celui puisse se régler un jour – je n'ai pour ma part pas les compétences pour y regarder de plus près.

**Comment by MokuJinJin** [comment]
> Oui je comprends, c'est dommage, l'idée était attirante sur le papier. Et en effet, le lien vers l'autre bug n'a pas avancé depuis quelques mois.
> 
> Merci en tout cas pour cet échange et à l'auteur d'æneria pour le travail, en espérant que celui puisse se régler un jour – je n'ai pour ma part pas les compétences pour y regarder de plus près.

J'ai les capacités de faire les modifications, j'ai bien envie de reprendre le projet.
j'ai déjà réussi à changer le mode de connexion à la nouvelle API

**Comment by SimonMellerin** [comment]
Hi @ericgaspar , 

I think, I see where is the bug here. 

In `scripts/install` and `scripts/upgrade` we create access only for admin user. 

Instead, access should be created for each yunohost users like it is done in `hooks/post_app_addaccess`

I don't really know how to properly do that, do you have an idea ?

Thanks

**Comment by SimonMellerin** [comment]
It also seems that ldap integration is broken :/ 

I'm currently adpating this package for aeneria V2, I'm gonna also check this point. But if you have an hint... may be something change on yunohost about ldap ?

**Comment by SimonMellerin** [comment]
or maybe @yalh76 can help us ?

**Comment by SimonMellerin** [comment]
Ce ticket sera résolu avec https://github.com/YunoHost-Apps/aeneria_ynh/pull/44
