### ISSUE TITLE
Maj vers æneria V2.0.x

### ISSUE THREAD

**Issue by laboitemail** [YunoHost-Apps/aeneria_ynh#45]
Une nouvelle version est disponible corrigeant le lien avec la nouvelle API Enedis
merci pour le travail d'intégration dans yunohost

**Comment by SimonMellerin** [comment]
Bonjour,

Le travail est en cours !

voir https://github.com/YunoHost-Apps/aeneria_ynh/pull/44

**Comment by SimonMellerin** [comment]
La MR citée au dessus est maintenant prête à être testée.

La plupart des utilisateurs d'æneria l'utilisent via son paquet YunoHost, cette version 2.0.x n'a donc pas été beaucoup éprouvée pour le moment (juste par moi en faite ^^). 

Avant merger cette MR, j'aimerais donc avoir quelques bêta-testeurs pour me faire des retours.

Pour mettre à jour votre instance d'æneria avec cette version de test, lancez :

`sudo yunohost app upgrade aeneria -u https://github.com/YunoHost-Apps/aeneria_ynh/tree/aeneria-v2  --force`

**À noter** : le système de consentement côté Enedis ayant beaucoup évolué, il vous faudra refaire le parcours via l'esapce Enedis.

Je ne vous donne volontairement pas plus d'indications sur le fonctionnement de l'app : ça va me permettre de valider si l'interface est suffisamment intuitive :wink: 

Si vous testez cette version, merci de me faire un signe sur ce ticket pour que je sache à peu près combien de personnes tentent l'aventure :pray:

**Comment by SimonMellerin** [comment]
La MR citée au dessus est maintenant prête à être testée.

La plupart des utilisateurs d'æneria l'utilisent via son paquet YunoHost, cette version 2.0.x n'a donc pas été beaucoup éprouvée pour le moment (juste par moi en faite ^^).

Avant merger cette MR, j'aimerais donc avoir quelques bêta-testeurs pour me faire des retours.

Pour mettre à jour votre instance d'æneria avec cette version de test, lancez :

`sudo yunohost app upgrade aeneria -u https://github.com/YunoHost-Apps/aeneria_ynh/tree/aeneria-v2  --force`

À noter : le système de consentement côté Enedis ayant beaucoup évolué, il vous faudra refaire le parcours via l'esapce Enedis.

Je ne vous donne volontairement pas plus d'indications sur le fonctionnement de l'app : ça va me permettre de valider si l'interface est suffisamment intuitive 😉

Si vous testez cette version, merci de me faire un signe sur ce ticket pour que je sache à peu près combien de personnes tentent l'aventure 🙏

**Comment by pnizet** [comment]
J'en suis ! 
Premiere chose : il faut que aeneria soit sur son propre domaine.
J'ai crée un sous-domaine, déplacé aeneria, puis lancé la mise à jour avec succes.
J'ai ensuite touvé ou il fallait mettre à jour la connexion avec Enedis.
bon faut pas etre préssé avec le site de ENEDIS, mais j'ai eu un message de succès, je regarderai plus tard pour voir si les données se rafraichissent bien !

Merci pour la MAJ, tout à l'air de marcher

**Comment by laboitemail** [comment]
mise à jour réussie facilement après création d'un sous-domaine (et d'un certificat)
j'ai pu garder mon historique de données 
rétablir le partage de données avec Enedis (j'ai un trou de 4 mois mais c'est un autre problème)
j'attends de voir si la mise à jour des données fonctionne correctement

merci pour la MAJ !

**Comment by jbarrere** [comment]
Merci beaucoup pour tout ce travail et la mise à jour, je vais aussi la tester !

**Comment by sereinity** [comment]
Hello, je me prend cette erreur :

```
Info: WARNING - PHP Parse error:  Unclosed '{' on line 14 in /var/www/aeneria/src/Security/YnhLdapUserProvider.php on line 89
```

**Comment by sereinity** [comment]
à rien n’y comprendre, c’est passé :eyes: cette fois ci.

Edit: sûrement grâce à https://github.com/YunoHost-Apps/aeneria_ynh/commit/adc2a721a46d2c44701f64ac3eeebd20aef379db

**Comment by sereinity** [comment]
Erreur 500 permanente:
```
[2024-01-09T13:19:15.888349+00:00] request.INFO: Matched route "app.root". {"route":"app.root","route_parameters":{"_route":"app.root","route":"app.home","permanent":true,"_controller":"Symfony\\Bundle\\FrameworkBundl\\Controller\\RedirectController"},"request_uri":"https://redacted.domain/","method":"GET"} []
[2024-01-09T13:19:15.894859+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Ldap\Exception\LdapException: "The LDAP PHP extension is not enabled." at /var/www/aeneria/vendor/symfony/ldap/Adapter/ExtLdap/Adapter.php line 29 {"exception":"[object] (Symfony\\Component\\Ldap\\Exception\\LdapException(code: 0): The LDAP PHP extension is not enabled. at /var/www/aeneria/vendor/symfony/ldap/Adapter/ExtLdap/Adapter.php:29)"} []
```

**Comment by SimonMellerin** [comment]
hum je regarde ça, désolé, j'étaits en train d'essayer de comprendre pourquoi la CI merdouillait, j'ai cassé cette version pendant quelques minutes...

**Comment by SimonMellerin** [comment]
@sereinity  peux-tu réessayer ? ça devrait être bon

**Comment by jbarrere** [comment]
mise à jour impeccable :
- ajout d'un sous domaine
- lier l'application sur ce sous domaine
- appliquer la mise à jour
- ajout du consentement

Félicitations, l'UI est très simple et très pratique à configurer !

J'ai eu de gros problèmes pour récupérer les données (erreurs, 404, etc...), j'ai passé un peu de temps à tenter de debug, puis j'ai vu les commentaires sur l'issue :)

Je viens de relancer un upgrade :
` sudo yunohost app upgrade aeneria -u https://github.com/YunoHost-Apps/aeneria_ynh/tree/aeneria-v2  --force`

J'ai forcé un fetch pour le 05/01 : 
`/usr/bin/php8.2 /var/www/aeneria/bin/console aeneria:fetch-data -d "2024-01-05"`

![image](https://github.com/YunoHost-Apps/aeneria_ynh/assets/1651392/148a7fab-af77-48ed-97db-fff1d914ccdb)

impeccable, merci beaucoup !

**Comment by sereinity** [comment]
> @sereinity peux-tu réessayer ? ça devrait être bon

c’est bon, plus de 500, j’ai pu fetch les données, je test un peu la version

**Comment by laboitemail** [comment]
avec la nouvelle version, j'ai pu récupérer les dernières données et compléter les mois manquants.
tout semble fonctionner.
merci beaucoup !!

**Comment by NoWiS-** [comment]
J'ai mis a jour hier, et j'ai aussi pu récupérer les dernières données et compléter les mois manquants sans problème.

La synchro de cette nuit a par contre été partielle:

10/01/2024 03:15:06 |   | app.INFO: EnedisDataConnectProxified - Data fetched {"feed":1,"date":"2024-01-09"} []
-- | -- | --
10/01/2024 03:15:06 |   | app.ERROR:  ProxifiedEnedisDataConnect - Error while fetching data  {"feed":1,"date":"2024-01-09","exception":"\"{\\u0022error\\u0022:\\u0022no_data_found\\u0022,\\u0022error_description\\u0022:\\u0022no  measure found for this usage point\\u0022}\""} []
10/01/2024 03:15:06 |   | http_client.INFO:  Response: "500  https://proxy.aeneria.com/enedis-data-connect/TOKEN/consumption-load-curve/2024-01-09/2024-01-10"  [] []
10/01/2024 03:15:05 |   | http_client.INFO:  Request: "GET  https://proxy.aeneria.com/enedis-data-connect/TOKEN/consumption-load-curve/2024-01-09/2024-01-10"  [] []
10/01/2024 03:15:05 |   | http_client.INFO:  Response: "200  https://proxy.aeneria.com/enedis-data-connect/TOKEN/daily-consumption/2024-01-09/2024-01-10"  [] []
10/01/2024 03:15:03 |   | http_client.INFO:  Request: "GET  https://proxy.aeneria.com/enedis-data-connect/TOKEN/daily-consumption/2024-01-09/2024-01-10"  [] []
-- | -- | --


(j'ai eu une notification d'erreur, mais il me semble avoir bien toutes les infos dans le dashboard)

**Comment by SimonMellerin** [comment]
@NoWiS-  

Tu peux ignorer l'erreur `app.ERROR: ProxifiedEnedisDataConnect - Error while fetching data {"feed":1,"date":"2024-01-09","exception":""{\u0022error\u0022:\u0022no_data_found\u0022,\u0022error_description\u0022:\u0022no measure found for this usage point\u0022}""} []`, ça peut arriver si on va chercher les données trop tôt
 
Les autres erreurs peuvent être ignorées, elles découlent de la première (ou la dernière selon le sens de lecteur ^^)
